from fastapi import APIRouter
from typing import Dict, Any, List

router = APIRouter(prefix="/api/demo", tags=["Hackathon Deterministic Demo"])

DEMO_STAGES = [
    {
        "stage_id": 1,
        "label": "Stage 1: ICU Admission Baseline",
        "hour_from_admission": 0,
        "elapsed_time_label": "Hour 0 (Day 1)",
        "patient": {
            "patient_id": "DEMO-1042",
            "ward_id": "ICU-A",
            "ward_name": "ICU-A (Medical)",
            "bed": "ICU-A-04",
            "age": 69,
            "gender": "Male",
            "admission_diagnosis": "Post-operative Respiratory Failure",
            "current_risk": 17.0,
            "risk_category": "LOW",
            "risk_delta_12h": 0.0,
            "risk_velocity_label": "0.0% / 12h",
            "rapid_escalation": False,
            "confidence_level": "HIGH",
            "review_priority": 3,
            "vitals": {
                "temp_c": 36.8,
                "wbc": 7.4,
                "heart_rate": 78,
                "map": 82,
                "resp_rate": 16,
                "spo2": 98,
                "cvc_hours": 0.0,
                "foley_hours": 0.0,
                "vent_hours": 0.0,
                "device_burden": 0,
            },
            "shap_drivers": [
                {"name": "Baseline Age (69)", "value": 69, "shap": 0.12, "direction": "ELEVATES_RISK", "category": "Demographics"},
                {"name": "Normal Body Temperature (36.8°C)", "value": 36.8, "shap": -0.35, "direction": "REDUCES_RISK", "category": "Vital Signs"},
                {"name": "Normal Leukocyte Count (7.4 k/µL)", "value": 7.4, "shap": -0.28, "direction": "REDUCES_RISK", "category": "Laboratory"},
                {"name": "Zero Invasive Device Exposure", "value": 0, "shap": -0.42, "direction": "REDUCES_RISK", "category": "Invasive Devices"},
            ]
        },
        "co_patients": [
            {"patient_id": "DEMO-1043", "bed": "ICU-A-05", "risk": 14.0, "category": "LOW", "velocity": "+0.0%/12h", "rapid": False},
            {"patient_id": "DEMO-1044", "bed": "ICU-A-06", "risk": 19.0, "category": "LOW", "velocity": "+1.0%/12h", "rapid": False},
            {"patient_id": "DEMO-1045", "bed": "ICU-A-07", "risk": 16.0, "category": "LOW", "velocity": "+0.0%/12h", "rapid": False},
        ],
        "ward_status": {
            "ward_id": "ICU-A",
            "ward_risk_level": "LOW",
            "high_risk_count": 0,
            "rapidly_rising_count": 0,
            "risk_density": 0.165,
            "cluster_signal": False,
            "cluster_message": "Baseline surveillance state. No anomalous cluster signals.",
        },
        "narrative": "Patient DEMO-1042 admitted to ICU-A. Physiological vitals and baseline lab values are within normal limits. Calibrated infection risk is 17% (LOW)."
    },
    {
        "stage_id": 2,
        "label": "Stage 2: Device Placement & Early Monitoring",
        "hour_from_admission": 24,
        "elapsed_time_label": "Hour 24 (Day 2)",
        "patient": {
            "patient_id": "DEMO-1042",
            "ward_id": "ICU-A",
            "ward_name": "ICU-A (Medical)",
            "bed": "ICU-A-04",
            "age": 69,
            "gender": "Male",
            "admission_diagnosis": "Post-operative Respiratory Failure",
            "current_risk": 29.0,
            "risk_category": "LOW",
            "risk_delta_12h": 6.0,
            "risk_velocity_label": "+6.0% / 12h",
            "rapid_escalation": False,
            "confidence_level": "HIGH",
            "review_priority": 3,
            "vitals": {
                "temp_c": 37.2,
                "wbc": 9.1,
                "heart_rate": 84,
                "map": 78,
                "resp_rate": 18,
                "spo2": 96,
                "cvc_hours": 24.0,
                "foley_hours": 24.0,
                "vent_hours": 12.0,
                "device_burden": 3,
            },
            "shap_drivers": [
                {"name": "Central Venous Catheter (24 hrs)", "value": 24.0, "shap": 0.31, "direction": "ELEVATES_RISK", "category": "Invasive Devices"},
                {"name": "Mechanical Ventilation (12 hrs)", "value": 12.0, "shap": 0.22, "direction": "ELEVATES_RISK", "category": "Invasive Devices"},
                {"name": "Mild Leukocyte Elevation (9.1 k/µL)", "value": 9.1, "shap": 0.14, "direction": "ELEVATES_RISK", "category": "Laboratory"},
                {"name": "Stable Core Temperature (37.2°C)", "value": 37.2, "shap": -0.15, "direction": "REDUCES_RISK", "category": "Vital Signs"},
            ]
        },
        "co_patients": [
            {"patient_id": "DEMO-1043", "bed": "ICU-A-05", "risk": 18.0, "category": "LOW", "velocity": "+4.0%/12h", "rapid": False},
            {"patient_id": "DEMO-1044", "bed": "ICU-A-06", "risk": 22.0, "category": "LOW", "velocity": "+3.0%/12h", "rapid": False},
            {"patient_id": "DEMO-1045", "bed": "ICU-A-07", "risk": 19.0, "category": "LOW", "velocity": "+3.0%/12h", "rapid": False},
        ],
        "ward_status": {
            "ward_id": "ICU-A",
            "ward_risk_level": "LOW",
            "high_risk_count": 0,
            "rapidly_rising_count": 0,
            "risk_density": 0.220,
            "cluster_signal": False,
            "cluster_message": "Standard ICU unit surveillance. Devices active.",
        },
        "narrative": "Central line and mechanical ventilation placed. Device dwell times begin accumulating. Infection probability nudges to 29% (LOW)."
    },
    {
        "stage_id": 3,
        "label": "Stage 3: CDC Surveillance Horizon (48h)",
        "hour_from_admission": 48,
        "elapsed_time_label": "Hour 48 (Day 3)",
        "patient": {
            "patient_id": "DEMO-1042",
            "ward_id": "ICU-A",
            "ward_name": "ICU-A (Medical)",
            "bed": "ICU-A-04",
            "age": 69,
            "gender": "Male",
            "admission_diagnosis": "Post-operative Respiratory Failure",
            "current_risk": 43.0,
            "risk_category": "MODERATE",
            "risk_delta_12h": 14.0,
            "risk_velocity_label": "+14.0% / 12h",
            "rapid_escalation": False,
            "confidence_level": "HIGH",
            "review_priority": 2,
            "vitals": {
                "temp_c": 37.8,
                "wbc": 12.2,
                "heart_rate": 96,
                "map": 72,
                "resp_rate": 22,
                "spo2": 94,
                "cvc_hours": 48.0,
                "foley_hours": 48.0,
                "vent_hours": 36.0,
                "device_burden": 3,
            },
            "shap_drivers": [
                {"name": "Central Venous Catheter (48 hrs)", "value": 48.0, "shap": 0.54, "direction": "ELEVATES_RISK", "category": "Invasive Devices"},
                {"name": "12h Temperature Upward Slope (+0.04°C/h)", "value": 0.04, "shap": 0.42, "direction": "ELEVATES_RISK", "category": "Vital Signs"},
                {"name": "Emerging Leukocytosis (12.2 k/µL)", "value": 12.2, "shap": 0.38, "direction": "ELEVATES_RISK", "category": "Laboratory"},
                {"name": "Moderate Oxygen Saturation (94%)", "value": 94.0, "shap": 0.16, "direction": "ELEVATES_RISK", "category": "Vital Signs"},
            ]
        },
        "co_patients": [
            {"patient_id": "DEMO-1043", "bed": "ICU-A-05", "risk": 32.0, "category": "MODERATE", "velocity": "+14.0%/12h", "rapid": False},
            {"patient_id": "DEMO-1044", "bed": "ICU-A-06", "risk": 28.0, "category": "LOW", "velocity": "+6.0%/12h", "rapid": False},
            {"patient_id": "DEMO-1045", "bed": "ICU-A-07", "risk": 24.0, "category": "LOW", "velocity": "+5.0%/12h", "rapid": False},
        ],
        "ward_status": {
            "ward_id": "ICU-A",
            "ward_risk_level": "MODERATE",
            "high_risk_count": 0,
            "rapidly_rising_count": 0,
            "risk_density": 0.318,
            "cluster_signal": False,
            "cluster_message": "Patient crosses CDC Day 3 HAI threshold. Elevated watch.",
        },
        "narrative": "Patient crosses the CDC Day 3 HAI surveillance threshold (≥48h). Temperature begins upward drift (37.8°C) with leukocytosis (12.2 k/µL). Risk crosses into MODERATE (43%)."
    },
    {
        "stage_id": 4,
        "label": "Stage 4: Risk Acceleration & Velocity Spike",
        "hour_from_admission": 54,
        "elapsed_time_label": "Hour 54 (Day 3 + 6h)",
        "patient": {
            "patient_id": "DEMO-1042",
            "ward_id": "ICU-A",
            "ward_name": "ICU-A (Medical)",
            "bed": "ICU-A-04",
            "age": 69,
            "gender": "Male",
            "admission_diagnosis": "Post-operative Respiratory Failure",
            "current_risk": 61.0,
            "risk_category": "HIGH",
            "risk_delta_12h": 22.0,
            "risk_velocity_label": "+22.0% / 12h",
            "rapid_escalation": True,
            "confidence_level": "HIGH",
            "review_priority": 1,
            "vitals": {
                "temp_c": 38.2,
                "wbc": 15.6,
                "heart_rate": 108,
                "map": 66,
                "resp_rate": 24,
                "spo2": 92,
                "cvc_hours": 54.0,
                "foley_hours": 54.0,
                "vent_hours": 42.0,
                "device_burden": 3,
            },
            "shap_drivers": [
                {"name": "Central Venous Catheter Exposure (54 hrs)", "value": 54.0, "shap": 0.72, "direction": "ELEVATES_RISK", "category": "Invasive Devices"},
                {"name": "Core Temperature Rise (38.2°C)", "value": 38.2, "shap": 0.58, "direction": "ELEVATES_RISK", "category": "Vital Signs"},
                {"name": "Rapid WBC Escalation (15.6 k/µL)", "value": 15.6, "shap": 0.51, "direction": "ELEVATES_RISK", "category": "Laboratory"},
                {"name": "Declining Mean Arterial Pressure (66 mmHg)", "value": 66.0, "shap": 0.32, "direction": "ELEVATES_RISK", "category": "Vital Signs"},
            ]
        },
        "co_patients": [
            {"patient_id": "DEMO-1043", "bed": "ICU-A-05", "risk": 58.0, "category": "MODERATE", "velocity": "+26.0%/12h", "rapid": True},
            {"patient_id": "DEMO-1044", "bed": "ICU-A-06", "risk": 48.0, "category": "MODERATE", "velocity": "+20.0%/12h", "rapid": True},
            {"patient_id": "DEMO-1045", "bed": "ICU-A-07", "risk": 36.0, "category": "MODERATE", "velocity": "+12.0%/12h", "rapid": False},
        ],
        "ward_status": {
            "ward_id": "ICU-A",
            "ward_risk_level": "HIGH",
            "high_risk_count": 1,
            "rapidly_rising_count": 2,
            "risk_density": 0.508,
            "cluster_signal": False,
            "cluster_message": "Multiple co-located escalations forming in ICU-A.",
        },
        "narrative": "Acute physiological escalation: Temp rises to 38.2°C, WBC spikes to 15.6 k/µL. 12-hour velocity (+22.0%/12h) trips the Rapid Escalation alert. Risk climbs to 61% (HIGH)."
    },
    {
        "stage_id": 5,
        "label": "Stage 5: Critical Risk & Explainability (WHY?)",
        "hour_from_admission": 60,
        "elapsed_time_label": "Hour 60 (Day 3 + 12h)",
        "patient": {
            "patient_id": "DEMO-1042",
            "ward_id": "ICU-A",
            "ward_name": "ICU-A (Medical)",
            "bed": "ICU-A-04",
            "age": 69,
            "gender": "Male",
            "admission_diagnosis": "Post-operative Respiratory Failure",
            "current_risk": 82.0,
            "risk_category": "CRITICAL",
            "risk_delta_12h": 39.0,
            "risk_velocity_label": "+39.0% / 12h",
            "rapid_escalation": True,
            "confidence_level": "HIGH",
            "review_priority": 1,
            "vitals": {
                "temp_c": 38.6,
                "wbc": 18.4,
                "heart_rate": 114,
                "map": 62,
                "resp_rate": 26,
                "spo2": 91,
                "cvc_hours": 60.0,
                "foley_hours": 60.0,
                "vent_hours": 48.0,
                "device_burden": 3,
            },
            "shap_drivers": [
                {"name": "Central Venous Catheter Exposure (60 hrs)", "value": 60.0, "shap": 0.84, "direction": "ELEVATES_RISK", "category": "Invasive Devices"},
                {"name": "12h Core Temp Upward Trend (38.6°C)", "value": 38.6, "shap": 0.62, "direction": "ELEVATES_RISK", "category": "Vital Signs"},
                {"name": "24h Leukocytosis Spike (+8.2 k/µL to 18.4)", "value": 18.4, "shap": 0.53, "direction": "ELEVATES_RISK", "category": "Laboratory"},
                {"name": "Lactate Accumulation (2.8 mmol/L)", "value": 2.8, "shap": 0.39, "direction": "ELEVATES_RISK", "category": "Laboratory"},
                {"name": "Platelet Nadir & Decline (95 k/µL)", "value": 95.0, "shap": 0.28, "direction": "ELEVATES_RISK", "category": "Laboratory"},
            ]
        },
        "co_patients": [
            {"patient_id": "DEMO-1043", "bed": "ICU-A-05", "risk": 74.0, "category": "HIGH", "velocity": "+42.0%/12h", "rapid": True},
            {"patient_id": "DEMO-1044", "bed": "ICU-A-06", "risk": 68.0, "category": "HIGH", "velocity": "+40.0%/12h", "rapid": True},
            {"patient_id": "DEMO-1045", "bed": "ICU-A-07", "risk": 52.0, "category": "MODERATE", "velocity": "+28.0%/12h", "rapid": True},
        ],
        "ward_status": {
            "ward_id": "ICU-A",
            "ward_risk_level": "HIGH",
            "high_risk_count": 3,
            "rapidly_rising_count": 4,
            "risk_density": 0.690,
            "cluster_signal": True,
            "cluster_message": "Potential cluster requiring IPC review.",
        },
        "narrative": "Patient reaches CRITICAL RISK (82.0%). Trajectory velocity is +3.25%/hr. TreeSHAP attribution pinpoints CVC dwell + temperature upward velocity + leukocytosis spike."
    },
    {
        "stage_id": 6,
        "label": "Stage 6: Spatial Contagion Cluster & Priority Rounding",
        "hour_from_admission": 66,
        "elapsed_time_label": "Hour 66 (Day 3 + 18h)",
        "patient": {
            "patient_id": "DEMO-1042",
            "ward_id": "ICU-A",
            "ward_name": "ICU-A (Medical)",
            "bed": "ICU-A-04",
            "age": 69,
            "gender": "Male",
            "admission_diagnosis": "Post-operative Respiratory Failure",
            "current_risk": 84.0,
            "risk_category": "CRITICAL",
            "risk_delta_12h": 23.0,
            "risk_velocity_label": "+23.0% / 12h",
            "rapid_escalation": True,
            "confidence_level": "HIGH",
            "review_priority": 1,
            "vitals": {
                "temp_c": 38.8,
                "wbc": 19.8,
                "heart_rate": 118,
                "map": 59,
                "resp_rate": 28,
                "spo2": 90,
                "cvc_hours": 66.0,
                "foley_hours": 66.0,
                "vent_hours": 54.0,
                "device_burden": 3,
            },
            "shap_drivers": [
                {"name": "Central Venous Catheter Exposure (66 hrs)", "value": 66.0, "shap": 0.88, "direction": "ELEVATES_RISK", "category": "Invasive Devices"},
                {"name": "Sustained Pyrexia (38.8°C)", "value": 38.8, "shap": 0.67, "direction": "ELEVATES_RISK", "category": "Vital Signs"},
                {"name": "Severe Leukocytosis (19.8 k/µL)", "value": 19.8, "shap": 0.58, "direction": "ELEVATES_RISK", "category": "Laboratory"},
                {"name": "Hemodynamic Instability (MAP 59 mmHg)", "value": 59.0, "shap": 0.44, "direction": "ELEVATES_RISK", "category": "Vital Signs"},
            ]
        },
        "co_patients": [
            {"patient_id": "DEMO-1043", "bed": "ICU-A-05", "risk": 86.0, "category": "CRITICAL", "velocity": "+28.0%/12h", "rapid": True},
            {"patient_id": "DEMO-1044", "bed": "ICU-A-06", "risk": 78.0, "category": "HIGH", "velocity": "+30.0%/12h", "rapid": True},
            {"patient_id": "DEMO-1045", "bed": "ICU-A-07", "risk": 64.0, "category": "HIGH", "velocity": "+28.0%/12h", "rapid": True},
        ],
        "ward_status": {
            "ward_id": "ICU-A",
            "ward_risk_level": "HIGH",
            "high_risk_count": 4,
            "rapidly_rising_count": 4,
            "risk_density": 0.780,
            "cluster_signal": True,
            "cluster_message": "Potential cluster requiring IPC review.",
            "recommendation": "Spatial contagion detected in ICU-A. Disinfection dispatched, bundle audits triggered for Beds 04-07."
        },
        "priority_rounding_roster": [
            {"rank": 1, "patient_id": "DEMO-1043", "bed": "ICU-A-05", "risk": 86.0, "velocity": "+28.0%/12h", "priority": 1, "action": "Immediate line bundle audit & culture review"},
            {"rank": 2, "patient_id": "DEMO-1042", "bed": "ICU-A-04", "risk": 84.0, "velocity": "+23.0%/12h", "priority": 1, "action": "Assess CVC line removal readiness"},
            {"rank": 3, "patient_id": "DEMO-1044", "bed": "ICU-A-06", "risk": 78.0, "velocity": "+30.0%/12h", "priority": 1, "action": "Catheter insertion site inspection"},
            {"rank": 4, "patient_id": "DEMO-1045", "bed": "ICU-A-07", "risk": 64.0, "velocity": "+28.0%/12h", "priority": 1, "action": "Environmental contact precaution review"},
        ],
        "narrative": "ICU-A Cluster Anomaly Radar triggers: 'Potential cluster requiring IPC review.' Beds 04, 05, 06, 07 are prioritized for immediate infection-prevention rounding."
    }
]


@router.get("/scenario", response_model=Dict[str, Any])
def get_demo_scenario():
    """
    Returns the complete deterministic 6-stage clinical scenario
    progressing DEMO-1042 (17% -> 29% -> 43% -> 61% -> 82% -> 84%) and ICU-A cluster.
    """
    return {
        "scenario_name": "HAI-Sentinel National Hackathon Deterministic Demonstration",
        "scenario_id": "DEMO-1042-CLABSI-ICU-A",
        "target_duration_seconds": 60,
        "offline_ready": True,
        "stages": DEMO_STAGES,
        "scientific_disclaimer": "Deterministic clinical demonstration scenario for hackathon judging. Operates 100% offline without remote dependencies."
    }
