"""
HAI-Sentinel Synthetic ICU Clinical Cohort Generator
===================================================
Generates a physiologically coherent, longitudinal EHR dataset for ICU patients
aligned with CDC/NHSN surveillance definitions for Healthcare-Associated Infections (HAIs).

IMPORTANT NOTICE:
All records generated by this module are SYNTHETIC RESEARCH / DEMO DATA for the
HAI-Sentinel prototype. No real patient identifiers or protected health information (PHI)
are included.
"""

import os
import json
import numpy as np
import pandas as pd
from datetime import datetime, timedelta
from typing import Dict, List, Tuple


def generate_synthetic_icu_cohort(
    n_patients: int = 250,
    seed: int = 42,
    output_dir: str = "data/demo"
) -> Tuple[pd.DataFrame, pd.DataFrame]:
    """
    Generates a synthetic longitudinal ICU cohort with:
    1. Static patient demographics & admission baseline
    2. Dynamic hourly clinical time-series (vitals, labs, device exposures, medications)
    3. Target labeling strictly following CDC/NHSN criteria (>48h post-admission onset)
    """
    np.random.seed(seed)
    os.makedirs(output_dir, exist_ok=True)

    wards = ["ICU-A (Medical)", "ICU-B (Surgical)", "ICU-C (Cardiac)", "Ward-3 (Stepdown)"]
    ward_probs = [0.4, 0.3, 0.2, 0.1]

    patients_meta = []
    timeseries_records = []

    start_date = datetime(2026, 8, 1, 8, 0, 0)

    # Specific deterministic demo patient: DEMO-1042
    demo_patient_id = "DEMO-1042"

    for p_idx in range(n_patients):
        if p_idx == 0:
            patient_id = demo_patient_id
        else:
            cand_id = 1100 + p_idx
            patient_id = f"DEMO-{cand_id}"
        
        # Clinical Demographics
        age = int(np.random.normal(63, 14))
        age = max(18, min(92, age))
        gender = "M" if np.random.rand() > 0.45 else "F"
        ward = "ICU-A (Medical)" if patient_id == demo_patient_id else np.random.choice(wards, p=ward_probs)
        bed = f"{ward.split()[0]}-{np.random.randint(1, 25):02d}"
        
        # Length of stay in ICU (between 48 and 168 hours)
        icu_los_hours = int(np.random.exponential(scale=40)) + 48
        icu_los_hours = min(168, max(48, icu_los_hours))
        
        admission_time = start_date + timedelta(hours=int(np.random.randint(0, 72)))
        
        # Comorbidity index (Charlson)
        charlson = int(np.random.choice([0, 1, 2, 3, 4, 5, 6], p=[0.15, 0.25, 0.25, 0.15, 0.1, 0.05, 0.05]))
        recent_surgery = 1 if ("Surgical" in ward or np.random.rand() < 0.3) else 0

        # HAI Label Assignment following CDC/NHSN criteria
        # Base prevalence in ICU ~12-16%
        if patient_id == demo_patient_id:
            develops_hai = 1
            hai_onset_hour = 60  # Onset at hour 60 (well past the 48h CDC mark)
            hai_type = "CLABSI"
        else:
            # Random assignment influenced by risk factors (devices, age, comorbidities)
            risk_latent = (
                0.08 
                + 0.04 * (charlson >= 3)
                + 0.05 * recent_surgery
                + 0.04 * (age > 65)
                + (0.08 if "ICU-A" in ward else 0.0) # Ward A has localized cluster simulation
            )
            develops_hai = 1 if np.random.rand() < risk_latent else 0
            if develops_hai:
                # HAI onset occurs strictly after 48 hours
                hai_onset_hour = int(np.random.randint(49, max(50, icu_los_hours - 6)))
                hai_type = np.random.choice(["CLABSI", "CAUTI", "VAP", "Sepsis-Unspecified"], p=[0.4, 0.3, 0.2, 0.1])
            else:
                hai_onset_hour = None
                hai_type = "None"

        # Baseline physiological parameters
        base_hr = np.random.normal(78, 8)
        base_temp = np.random.normal(36.8, 0.25)
        base_sbp = np.random.normal(122, 12)
        base_dbp = np.random.normal(76, 8)
        base_rr = np.random.normal(16, 2)
        base_spo2 = np.random.normal(97.5, 1.2)
        base_wbc = np.random.normal(7.5, 1.5)
        base_plt = np.random.normal(230, 40)
        base_cr = np.random.normal(1.0, 0.25)
        base_lactate = np.random.normal(1.2, 0.3)

        # Device exposures
        has_cvc = 1 if (patient_id == demo_patient_id or np.random.rand() < 0.65) else 0
        has_foley = 1 if (patient_id == demo_patient_id or np.random.rand() < 0.75) else 0
        has_vent = 1 if (patient_id == demo_patient_id or np.random.rand() < 0.35) else 0

        cvc_start = int(np.random.randint(0, 12)) if has_cvc else None
        foley_start = int(np.random.randint(0, 6)) if has_foley else None
        vent_start = int(np.random.randint(0, 24)) if has_vent else None

        # Generate hourly longitudinal records (from hour 0 to icu_los_hours)
        for h in range(icu_los_hours):
            current_time = admission_time + timedelta(hours=h)
            
            # Device exposure durations
            cvc_hrs = max(0, h - cvc_start) if (has_cvc and h >= cvc_start) else 0
            foley_hrs = max(0, h - foley_start) if (has_foley and h >= foley_start) else 0
            vent_hrs = max(0, h - vent_start) if (has_vent and h >= vent_start) else 0
            device_burden = int(bool(cvc_hrs > 0)) + int(bool(foley_hrs > 0)) + int(bool(vent_hrs > 0))

            # Physiological progression
            # If HAI patient approaching onset: simulate realistic progressive derangement
            if develops_hai and h >= (hai_onset_hour - 24):
                # Escalation phase (t-24h to t_onset)
                progression = min(1.0, (h - (hai_onset_hour - 24)) / 24.0)
                
                # Temperature elevation (spikes up to 38.8C)
                temp = base_temp + progression * np.random.uniform(1.2, 2.1) + np.random.normal(0, 0.15)
                # Heart rate tachycardia
                hr = base_hr + progression * np.random.uniform(22, 38) + np.random.normal(0, 2.5)
                # Blood pressure drop (vasodilation)
                sbp = base_sbp - progression * np.random.uniform(18, 30) + np.random.normal(0, 3)
                dbp = base_dbp - progression * np.random.uniform(12, 20) + np.random.normal(0, 2)
                rr = base_rr + progression * np.random.uniform(6, 12) + np.random.normal(0, 1)
                spo2 = max(88.0, base_spo2 - progression * np.random.uniform(2, 5) + np.random.normal(0, 0.5))
                # Leukocytosis (WBC spikes to 14 - 22)
                wbc = base_wbc + progression * np.random.uniform(6.5, 13.0) + np.random.normal(0, 0.4)
                # Thrombocytopenia (Platelet consumption)
                plt = max(50.0, base_plt - progression * np.random.uniform(40, 90) + np.random.normal(0, 5))
                # Renal / metabolic markers
                cr = base_cr + progression * np.random.uniform(0.4, 1.1) + np.random.normal(0, 0.05)
                lactate = base_lactate + progression * np.random.uniform(1.0, 2.8) + np.random.normal(0, 0.1)
                broad_spec_abx = 1 if h >= (hai_onset_hour - 6) else 0
            else:
                # Normal or fluctuating ICU course without HAI
                temp = base_temp + np.random.normal(0, 0.2)
                hr = base_hr + np.random.normal(0, 3.5)
                sbp = base_sbp + np.random.normal(0, 4.0)
                dbp = base_dbp + np.random.normal(0, 3.0)
                rr = base_rr + np.random.normal(0, 1.2)
                spo2 = min(100.0, max(92.0, base_spo2 + np.random.normal(0, 0.6)))
                wbc = max(3.5, base_wbc + np.random.normal(0, 0.3))
                plt = max(100.0, base_plt + np.random.normal(0, 4.0))
                cr = max(0.5, base_cr + np.random.normal(0, 0.04))
                lactate = max(0.6, base_lactate + np.random.normal(0, 0.08))
                broad_spec_abx = 1 if (recent_surgery and h < 24) else 0

            map_val = (2 * dbp + sbp) / 3.0

            # Target label for this timestamp t (predicting HAI event in next 24 hours)
            if develops_hai:
                target_24h = 1 if (h < hai_onset_hour <= h + 24) else 0
            else:
                target_24h = 0

            timeseries_records.append({
                "patient_id": patient_id,
                "hour_from_admission": h,
                "timestamp": current_time.isoformat(),
                "heart_rate": round(float(hr), 1),
                "temp_c": round(float(temp), 2),
                "sbp": round(float(sbp), 1),
                "dbp": round(float(dbp), 1),
                "map": round(float(map_val), 1),
                "resp_rate": round(float(rr), 1),
                "spo2": round(float(spo2), 1),
                "wbc": round(float(wbc), 2),
                "platelets": round(float(plt), 1),
                "creatinine": round(float(cr), 2),
                "lactate": round(float(lactate), 2),
                "cvc_duration_hours": cvc_hrs,
                "foley_duration_hours": foley_hrs,
                "vent_duration_hours": vent_hrs,
                "total_device_burden": device_burden,
                "broad_spec_antibiotics_72h": broad_spec_abx,
                "target_hai_next_24h": target_24h,
            })

        patients_meta.append({
            "patient_id": patient_id,
            "ward": ward,
            "bed": bed,
            "age": age,
            "gender": gender,
            "charlson_comorbidity_index": charlson,
            "recent_surgery": recent_surgery,
            "admission_time": admission_time.isoformat(),
            "icu_los_hours": icu_los_hours,
            "develops_hai": develops_hai,
            "hai_onset_hour": hai_onset_hour,
            "hai_type": hai_type,
            "is_demo_patient": (patient_id == demo_patient_id)
        })

    df_meta = pd.DataFrame(patients_meta)
    df_ts = pd.DataFrame(timeseries_records)

    # Save to disk
    meta_path = os.path.join(output_dir, "synthetic_patients_metadata.csv")
    ts_path = os.path.join(output_dir, "synthetic_icu_timeseries.csv")
    df_meta.to_csv(meta_path, index=False)
    df_ts.to_csv(ts_path, index=False)

    summary = {
        "dataset_name": "HAI-Sentinel Synthetic ICU Cohort (NHSN-Aligned)",
        "creation_timestamp": datetime.utcnow().isoformat(),
        "n_patients": len(df_meta),
        "total_hourly_records": len(df_ts),
        "hai_prevalence_pct": round(float(df_meta["develops_hai"].mean() * 100), 2),
        "wards": wards,
        "features_included": list(df_ts.columns),
        "scientific_disclaimer": "SYNTHETIC BENCHMARK DATA. No PHI. Strictly for prototype validation."
    }
    with open(os.path.join(output_dir, "cohort_summary.json"), "w") as f:
        json.dump(summary, f, indent=2)

    print(f"[COHORT GENERATOR] Generated {len(df_meta)} patients with {len(df_ts)} longitudinal records.")
    return df_meta, df_ts


if __name__ == "__main__":
    generate_synthetic_icu_cohort()
